<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Srinivas-VAIO" ignored="4" name="Default test" tests="1" failures="1" timestamp="09 Sep 2019 03:01:51 GMT" time="38.0" errors="0">
  <testcase name="verifyTalksPage" time="29.27" classname="feature.UITest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.lang.String.contains(String.java:2133)
at pages.TalksPage.checkTalksPageContentDisplayed(TalksPage.java:28)
at feature.UITest.verifyTalksPage(UITest.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyTalksPage -->
  <testcase name="verifyBlogPage" time="0.0" classname="feature.UITest">
    <ignored/>
  </testcase> <!-- verifyBlogPage -->
  <testcase name="verifyAboutUsPage" time="0.0" classname="feature.UITest">
    <ignored/>
  </testcase> <!-- verifyAboutUsPage -->
  <testcase name="verifyContactUsPage" time="0.0" classname="feature.UITest">
    <ignored/>
  </testcase> <!-- verifyContactUsPage -->
  <testcase name="verifyWorkPage" time="0.0" classname="feature.UITest">
    <ignored/>
  </testcase> <!-- verifyWorkPage -->
</testsuite> <!-- Default test -->
